### ISSUE TITLE
unable to generate request in macOS Big Sur

### ISSUE THREAD

**Issue by appsird** [Alamofire/AlamofireImage#438]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

I integrate Alamofire/AlamofireImage into a single view app using the Swift Package Manager. I then import both Alamofire nd AlamofireImage into the ViewController. This compiles clean.

I then add a single Alamofire.request which generates an error stating:

> Module 'Alamofire' has no member named 'request'

## What did you expect to happen?

I understand this should work in macOS releases 10.12+

## What happened instead?

The request generates a syntax error in Xcode

> Module 'Alamofire' has no member named 'request'

Project attached.

## Alamofire Environment

Alamofire 5.4.1
AlamofireImage 4.1.0
Xcode 12.4
Swift 5
MacBook Pro (intel)
macOS 11.2 

## Demo Project

[AFTest.zip](https://github.com/Alamofire/AlamofireImage/files/5939997/AFTest.zip)

**Comment by appsird** [comment]
I read the Alamofire 5.0 Migration Guide and see the issue.

Alamofire.request() is deprecated in favor of AF.request()

Thanks
